# |------------------------------------------------------------------------| #
# | #                                                                    # | #
# | #                -----------------------------------                 # | #
# | #                | SecurityCore v2.0.0 by xDec0de_ |                 # | #
# | #                -----------------------------------                 # | #
# | #                                                                    # | #
# |------------------------------------------------------------------------| #

AHS:
  Enabled: true
  BypassPerm: "sc.hiddensyntax.bypass"
  Notify:
    Permission: "sc.notify.hiddensyntax"
    Console: true
    Players: true
AntiTab:
  Enabled: true
  BypassPerm: "sc.bypass.antitab"
  Hide:
    All: false
    ListContains:
    - ":"
    ListExact:
    - "help"
    - "ver"
    - "version"
    - "pl"
    - "plugins"
    - "abo"
    - "about"
    - "?"
    - "icanhasbukkit"
WarnCMDs:
  BypassPerm: "sc.bypass.warncmd"
  Notify:
    Permission: "sc.notify.warncmd"
    Console: true
    Players: true
  List:
  - /op
  - /deop
BlockedCMDs:
  Enabled: true
  BypassPerm: "sc.bypass.blockcmd"
  Notify:
    Permission: "sc.notify.blockcmd"
    Console: true
    Players: true
  List:
  - /help
  - /ver
  - /version
  - /pl
  - /plugins
  - /abo
  - /about
  - /?
  - /icanhasbukkit
ReloadPerm: "sc.reload"
RedstoneLimiter:
  Enabled: true
  MaxPulsesPerSecond: 4
SCSetting:
  Permission: "sc.settings"
