name: ${project.name}
main: es.xdec0de.SecurityCore
author: xDec0de_
version: ${project.version}
depend: [ProtocolLib]
commands:
  ahs:
    usage: /<command>
    description: Main command of the plugin.