name: ${project.name}
main: es.xdec0de.securitycore.SecurityCore
author: xDec0de_
version: ${project.version}
commands:
  securitycore:
    usage: /<command>
    description: Main command of the plugin.
    aliases: [seccore]
